services:

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks: [flashsale]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"
    ports:
      - "2181:2181"
    healthcheck:
      test: [ "CMD", "bash", "-lc", "echo ruok >/dev/tcp/127.0.0.1/2181 && echo imok" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks: [flashsale]

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: "1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

      # 对外给宿主机（你本地跑 Spring Boot）用 localhost:9092
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT_INTERNAL"

      # 单机开发：replication 都设 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"

      # 关闭自动建 topic（避免 typo 乱建）
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

      # 让我们可以创建 12 partitions 的 topic
      KAFKA_NUM_PARTITIONS: "12"
    healthcheck:
      test: ["CMD", "bash", "-c", "kafka-topics --bootstrap-server localhost:9092 --list > /dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks: [flashsale]


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8880:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
    networks: [flashsale]

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" #Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks: [flashsale]

  authdb:
    container_name: authdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${AUTH_DB_NAME}
      MYSQL_USER: ${AUTH_DB_USER}
      MYSQL_PASSWORD: ${AUTH_DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - authdb_data:/var/lib/mysql
    extends:
      file: common-config.yml
      service: microservice-db-config

  catalogdb:
    container_name: catalogdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${CATALOG_DB_NAME}
      MYSQL_USER: ${CATALOG_DB_USER}
      MYSQL_PASSWORD: ${CATALOG_DB_PASS}
    ports:
      - "3307:3306"
    volumes:
      - catalogdb_data:/var:/lib/mysql
    extends:
      file: common-config.yml
      service: microservice-db-config

  inventorydb:
    container_name: inventorydb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${INVENTORY_DB_NAME}
      MYSQL_USER: ${INVENTORY_DB_USER}
      MYSQL_PASSWORD: ${INVENTORY_DB_PASS}
    ports:
      - "3308:3306"
    volumes:
      - inventorydb_data:/var/lib/mysql
    extends:
      file: common-config.yml
      service: microservice-db-config

  orderdb:
    container_name: orderdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${ORDER_DB_NAME}
      MYSQL_USER: ${ORDER_DB_USER}
      MYSQL_PASSWORD: ${ORDER_DB_PASS}
    ports:
      - "3309:3306"
    volumes:
      - orderdb_data:/var/lib/mysql
    extends:
      file: common-config.yml
      service: microservice-db-config


volumes:
  authdb_data:
  catalogdb_data:
  inventorydb_data:
  orderdb_data:
  redis_data:

networks:
  flashsale:
    driver: "bridge"