server:
  port: 8084

spring:
  application:
    name: order

  datasource:
    url: ${ORDER_DB_URL:jdbc:mysql://localhost:3309/orderdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${ORDER_DB_USER:order}
    password: ${ORDER_DB_PASS:orderpw}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false


inventory:
  base-url: http://localhost:8083
  timeout-ms: 1500

