server:
  port: 8083

spring:
  application:
    name: inventory

  datasource:
    url: ${INVENTORY_DB_URL:jdbc:mysql://localhost:3308/inventorydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${INVENTORY_DB_USER:inventory}
    password: ${INVENTORY_DB:PASS:inventorypw}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
