server:
  port: 8083

spring:
  application:
    name: inventory

  datasource:
    url: jdbc:mysql://localhost:3308/inventorydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: inventory
    password: inventorypw
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
