server:
  port: 8081

spring:
  application:
    name: auth

  datasource:
    url: ${AUTH_DB_URL:jdbc:mysql://localhost:3306/authdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${AUTH_DB_USER:auth}
    password: ${AUTH_DB_PASS:authpw}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

app:
  jwt:
    secret: ${JWT_SECRET:24a5b9e54cac54499777b9bc6f8f882a84346aeaf5e122094a14f4789b2d1db0}
    issuer: ${JWT_ISSUER:flash-sale-auth}
    expires-minutes: ${JWT_EXPIRES_MINUTES:60}